### ISSUE TITLE
Git plugin update broke since it doesn't fetch tags

### ISSUE THREAD

**Issue by mboersma** [deis/jenkins#12]
I worked around this temporarily in the workflow-cli job by adding a `git fetch --tags` command inline. I just wanted to note here that recent updates to Jenkins and plugins broke workflow-cli builds due to https://issues.jenkins-ci.org/browse/JENKINS-45164.

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/jenkins#1
